name: Notify Children Templates
on:
  push:
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - web-app-template
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: sripwoud/${{ matrix.repo }}
          event-type: template-sync
