name: Sync Template
on:
  repository_dispatch:
    types: [template-sync]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: AndreasAugustin/actions-template-sync@v2
        with:
          pr_title: "chore: upstream merge template repository"
          github_token: ${{ steps.app-token.outputs.token }}
          source_repo_path: sripwoud/agnostic-template
